# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkLibraries' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for NetworkLibraries
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.1'
end
