# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'TopSongWithJSON' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TopSongWithJSON

  pod 'Kingfisher', '~> 5.0'

end
